# Generated by Django 4.2.16 on 2024-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_submissionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=100)),
                ('event_code', models.CharField(choices=[('self_vkyc_initiated', 'Self Vkyc Initiated'), ('self_vkyc_submitted', 'Self Vkyc Submitted'), ('self_vkyc_verified', 'Self Vkyc Verified'), ('self_vkyc_booked', 'Schedule Vkyc Booked'), ('call_scheduled', 'Call Scheduled'), ('schedule_call_started', 'Scheduled Call Started'), ('schedule_call_ended', 'Scheduled Call Ended'), ('scheduled_vkyc_verified', 'Scheduled Vkyc Verified')], max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('time_stamp', models.CharField(max_length=100)),
                ('data', models.JSONField()),
            ],
        ),
    ]
