# Generated by Django 4.2.16 on 2024-09-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_submissionid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionid',
            name='submission_id',
            field=models.CharField(max_length=20),
        ),
    ]
